# Generated by Django 2.0.13 on 2019-03-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=60)),
                ('rg', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=80)),
            ],
        ),
    ]
